language: node_js

node_js:
- "0.11"

before_script:
  - npm install -g grunt-cli
  - psql -c 'create database travis_ci_test;' -U postgres
install: npm install
script: grunt test

    recipients:
      - ryojiosawa@gmail.com
      - supriya.bhat@gmail.com
      - jamesongamble@gmail.com
      - kevin.a.meurer@gmail.com
      - jomerinog@gmail.com
    on_success: always|never|change # default: always
    on_failure: always|never|change # default: always 

before_script: 
- npm install -g grunt-cli

after_script:
  # Install the Heroku package (or the Heroku toolbelt)
  - npm install heroku
  # Add your Heroku git repo:
  - git remote add heroku git@heroku.com:germ-tracker.git
  # Turn off warnings about SSH keys:
  - echo "Host heroku.com" >> ~/.ssh/config
  - echo "   StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "   CheckHostIP no" >> ~/.ssh/config
  - echo "   UserKnownHostsFile=/dev/null" >> ~/.ssh/config
  # Download and install Heroku toolbelt locally
  - wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
  # Clear your current Heroku SSH keys:
  - heroku keys:  clear
  # Add a new SSH key to Heroku
  - yes | heroku keys:add
  # Push to Heroku!
  - yes | git push heroku master
