# after_success: 
# - bash ./after_success.sh
language: node_js
node_js: 
- "0.11"
notifications: 
  email: 
    recipients: 
    - ryojiosawa@gmail.com
    - supriya.bhat@gmail.com
    - jamesongamble@gmail.com
    - kevin.a.meurer@gmail.com
    - jomerinog@gmail.com
    on_success: 
    - change
    on_failure: 
    - always
before_script: 
- npm install -g grunt-cli
deploy: 
  provider: heroku
  api_key: 
    secure: hq7OzqMO0xYRcC9ovApnKbbghd382Q8msAJiQ7GH+SPX5htuIf/UDB+vgT/uHuoOdHV2i0h2fy8r4GRkw+EY2VKz00oA2CTM5/Ztf25kV0Pq/D2cJ2gWJpkBDKtzF4i2F5pT/7uKeyBwjHFsG+v9/73DwenoShqVTZ/KXewDUCM=
  app: germ-tracker
