language: node_js

node_js:
- '0.11'

notifications:
  email:
    recipients:
      - ryojiosawa@gmail.com
      - supriya.bhat@gmail.com
    on_success:
      - change
    on_failure:
      - always
